import "./css/style.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        <div className="flex min-h-screen overflow-hidden flex-col h-screen overflow-hidden supports-[overflow:hidden]:overflow-hidden">
          {children}
        </div>
         <!--            This font is considered a proprietary software. To gain information about the laws regarding the use of these fonts, please visit www.fontiran.com            --------------------------------------------------------------------------------------            This set of fonts are used in this project under the license: (9M1VS5DP)            --------------------------------------------------------------------------------------            ...-->            <a target="_blank" href="https://fontiran.com/license/9M1VS5DP" >            <div style="width: 123px;font-size: 10px;" >             <img src="https://fontiran.com/storage/uploads/images/2023/1/badge2-minjcHOH8.png" width="100" height="100" alt="فونت ایران‌یکان">             <br>             <span style="text-align: justify;" >این وبسایت به صورت قانونی از فونت فونت ایران‌یکان استفاده میکند. </span>             </div>             </a>            
      </body>
    </html>
  );
}
